#!/usr/bin/env bash
# script installs nginx, ensures it's listening on port 80 and
# that a GET request(curl) to Nginx at root / return "Hello World!"

apt update
apt install -y nginx

cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location / {
		return 200 'Hello World!';
		add_header Content-Type text/plain;
	}
}
EOF

# Reload nginx
systemctl reload nginx
