#!/usr/bin/env bash
# Configures Nginx server so that "/redirect_me" is redirecting to another page
# with code '301 Moved Permanently'

# Check if the script is run as root
if [ "$(id -u)" -ne 0 ]; then
        exit 1
fi

cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
                return 200 'Hello World!';
                add_header Content-Type text/plain;
        }
}
EOF

cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80;
	return 301 https://youtube.com;
}
EOF

sudo service nginx restart
