#!/usr/bin/env bash
# Configures Nginx server so that "/redirect_me" is redirecting to another page
# with code '301 Moved Permanently'

# Check if the script is run as root
if [ "$(id -u)" -ne 0 ]; then
        exit 1
fi

apt update
apt install -y nginx

cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm;
        server_name _;

        location / {
                root /var/www/html;
                try_files \$uri \$uri/ =404;
                add_header Content-Type text/plain;
        }

        rewrite ^/redirect_me$ https://github.com/KenNyagz permanent;
}
EOF

sudo service nginx restart
