#!/usr/bin/env bash
# Configure nginx to have a custom 404

# Ensure script running as root
if [ "$(id -u)" -ne 0 ]; then
	exit 1
fi

apt update
apt install -y nginx

cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
                return 200 'Hello World!';
                add_header Content-Type text/plain;
        }
}
EOF

cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 80;
        return 301 https://youtube.com;
}
EOF

cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80 default_server;
        listen [::]:80 default_server;


	location / {
                return 200 'Hello World!';
                add_header Content-Type text/plain;
        }

	error_page 404 = /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
}
EOF

# Reload nginx
sudo service nginx restart
