#!/usr/bin/env bash
# Configure nginx to have a custom 404

# Ensure script running as root
if [ "$(id -u)" -ne 0 ]; then
	exit 1
fi

CUSTOM_404="Ceci n'est pas une page."

# Update the Nginx configuration to handle 404 errors
sed -i '/server {/a \
	error_page 404 /404.html;\n \
	location = /404.html {\n \
		internal;\n \
		echo "$CUSTOM_404";\n \
	}\n \
' /etc/nginx/sites-available/default

# Create the Custom 404 page
echo "$CUSTOM_404" > /var/www/html/404.html

# Reload nginx
sudo service nginx restart
