#!/usr/bin/env bash
# Configure nginx to have a custom 404

# Ensure script running as root
if [ "$(id -u)" -ne 0 ]; then
	exit 1
fi

cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
                return 200 'Hello World!';
                add_header Content-Type text/plain;
        }
}
EOF

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure nginx to have a custom 404
sed -i '/server {/a \
    error_page 404 /custom_404.html;\n \
    location = /404.html {\n \
        internal;\n \
    }\n \
' /etc/nginx/sites-available/default

# Reload nginx
sudo service nginx restart
