#!/usr/bin/env bash
# shellcheck disable=SC2154

sudo apt-get -y update
sudo apt-get install -y nginx

sudo sed -i "5i \\\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

sudo service nginx restart
