#!/usr/bin/env bash
# shellcheck disable=SC2154

sudo apt update
sudo apt install -y nginx

# sed -i "s/location / {/a\n add_header X-Served-By $host;/" /etc/nginx/sites-available/default
sudo sed -i 's/location \/ \{/a\\n add_header X-Served-By $host;/' /etc/nginx/sites-available/default

sudo service nginx restart
