#!/usr/bin/env bash
# shellcheck disable=SC2154

sudo apt update
sudo apt install -y haproxy

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 $(hostname)-web-01:80 check
    server web-02 $(hostname)-web-02:80 check
EOF

# Enable HAProxy management via init script
sudo systemctl enable haproxy

sudo systemctl restart haproxy
