#!/usr/bin/env bash
# shellcheck disable=SC2154

sudo apt update
sudo apt install -y haproxy

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 447462-web-01 54.236.17.14:80
    server 447462-web-02 18.209.223.91:80
EOF

# Enable HAProxy management via init script
sudo systemctl enable haproxy

sudo systemctl restart haproxy
