#!/usr/bin/env bash
# script that:
# 	Creates the file /var/run/myscript.pid containing its PID
#	Displays To infinity and beyond indefinitely
#	Displays I hate the kill command when receiving a SIGTERM signal
#	Displays Y U no love me?! when receiving a SIGINT signal
#	Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


sigterm_handler() {
    echo "I hate the kill command"
}

sigint_handler() {
    echo "Y U no love me?!"
}

sigquit_term_handler() {
    echo "Deleting PID file and terminating script..."
    rm /var/run/myscript.pid
    exit 0
}

trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_term_handler' SIGQUIT SIGTERM


echo "$$" > /var/run/myscript.pid

#trap 'echo "I hate the kil command"; rm -rf /var/run/myscript.pid; exit' 15 #SIGQUIT
#trap 'rm -rf /var/run/myscript.pid; exit' 3 #SIGINT
#trap 'Y U no love me?!exit' 2 #SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
