#!/usr/bin/env bash
#  script that displays the content of the file /etc/passwd.
# 	displays:
#		username
#		user id
#		Home directory path for the user

while read -r lines
do
	echo "$lines" | cut -d ":" -f 1,3,6
done < "/etc/passwd"
