#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while loop + IFS

# exec 3< /etc/passwd

while IFS=':' read -r username password uid gid uinfo homedir shell;
do
	echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user is here: $uinfo"
done < /etc/passwd

# exec 3<&-
