#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while loop + IFS

IFS=":"

exec 3< /etc/passwd

while IFS= read -r line <&3;
do
	echo "Line: $line"
done

exec 3<&-
