#!/usr/bin/env bash
# Script displays the visitor IP along with the HTTP status code from the Apache log file
#	Format: IP HTTP_CODE:
#		in a list format; <IP-address HTTP-code>

log_file="/var/log/apache2/access.log"

awk '{print $1, $9}' "$log_file"
