#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
# 	display hours from 0 to 12
# 	display minutes from 1 to 59

hours=0
minutes=1
echo "Hour: $hours"
while [ $hours -le 12 ];
do
    # echo "Hour: $hours"
    ((hours++))
    while [ $minutes -le 60 ];
    do
	if [ $minutes -eq 60 ]
	then
	    echo "Hour: $hours"
	else
	    echo $minutes
	fi
        ((minutes++))
    done
done
