#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while loop + IFS

IFS=":"

# exec 3< /etc/passwd

while IFS=":" read -r username passwd uid gid uinfo homedir shell;
do
	echo "The user $username is part of the $gid, lives in $homedir and rides $shell. $uid's place
		is protected by $passwd, more info about the user is here: $uinfo"
done

# exec 3<&-
