#!/usr/bin/env bash
#  configures an Ubuntu server to:
# 	resolve "localhost" to ip address 127.0.0.2
#	resolve "facebook.com" to ip address 8.8.8.8
echo "8.8.8.8	facebook.com" >> /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
