#!/usr/bin/env bash
# Configures nginx to run as the user'nginx' and listen on port 8080 on all active IPs

#service nginx stop

# Update Nginx configuration to run as nginx user
#sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx configuration to listen on port 8080
#sed i "s/80 default_/8080 default_/" /etc/nginx/sites-available/default

#chmod 644 /etc/nginx/nginx.conf

#sudo -u nginx service nginx start


# Create the nginx user if it doesn't exist
id -u nginx &>/dev/null || useradd -r -s /bin/false nginx

# Change the ownership of the nginx configuration directory and files
chown -R nginx:nginx /etc/nginx /var/log/nginx /var/lib/nginx

# Switch to the nginx user
exec su-exec nginx /usr/sbin/nginx -g "daemon off;"
