#!/usr/bin/env bash
# Configures nginx to run as the user'nginx' and listen on port 8080 on all active IPs

sudo sed i 's/80/8080/' /etc/nginx/sites-available/default

sudo chown -R nginx:nginx /var/log/nginx /var/lib/nginx

sudo -u nginx service nginx restart
